### PR TITLE
Fixing params spec-final

### PR DESCRIPTION
**Pull request by kentcdodds**
The expectations were commented out and incorrect. This fixes those :-)

### CODE REVIEW

**Comment by aaronfrost** [comment]
Thanks @kent.

**Comment by aaronfrost** [comment]
Merged from the BART. #achievementunlocked

**Comment by kentcdodds** [comment]
lol, what's the BART?

**Comment by kentcdodds** [comment]
Think [I got it](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=bart%20san%20francisco). Neat! Hope you're having an awesome time!

**Pull request merged**
